---
permalink: sg6000/replacing-sg6000-cn-controller.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, Replacing, replace, sg6000-cn, controller, remove, removing, removal, install, installing, installation 
summary: SG6000-CN 컨트롤러가 최적의 상태로 작동하지 않거나 오류가 발생한 경우 교체해야 할 수 있습니다. 
---
= SG6000-CN 컨트롤러를 교체합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SG6000-CN 컨트롤러가 최적의 상태로 작동하지 않거나 오류가 발생한 경우 교체해야 할 수 있습니다.

.시작하기 전에
* 교체할 컨트롤러와 부품 번호가 동일한 교체 컨트롤러가 있습니다. 컨트롤러 전면에 부착된 태그를 확인하여 부품 번호가 일치하는지 확인합니다.
* 컨트롤러에 연결된 각 케이블을 식별하는 라벨이 있습니다.
* 데이터 센터에서 물리적으로 교체할 컨트롤러를 가지고 있습니다.
+
link:locating-controller-in-data-center.html["데이터 센터에서 컨트롤러를 찾습니다"]



.이 작업에 대해
SG6000-CN 컨트롤러를 교체할 때 어플라이언스 스토리지 노드에 액세스할 수 없습니다. SG6000-CN 컨트롤러가 충분히 작동하는 경우 이 절차를 시작할 때 제어된 종료를 수행할 수 있습니다.


NOTE: StorageGRID 소프트웨어를 설치하기 전에 컨트롤러를 교체하는 경우 이 절차를 완료한 후 즉시 StorageGRID 어플라이언스 설치 프로그램에 액세스하지 못할 수 있습니다. 어플라이언스와 동일한 서브넷에 있는 다른 호스트에서 StorageGRID 어플라이언스 설치 프로그램에 액세스할 수 있지만 다른 서브넷에 있는 호스트에서는 액세스할 수 없습니다. 이 조건은 15분 내에 해결되어야 하며(원래 컨트롤러의 ARP 캐시 항목이 시간 초과될 때), 또는 로컬 라우터 또는 게이트웨이에서 수동으로 이전의 ARP 캐시 항목을 삭제하여 즉시 조건을 지울 수 있습니다.

.단계
. 어플라이언스의 현재 구성을 표시하고 기록하십시오.
+
.. 교체할 어플라이언스에 로그인합니다.
+
... 다음 명령을 입력합니다. `ssh admin@_grid_node_IP_`
... 에 나열된 암호를 입력합니다 `Passwords.txt` 파일.
... 루트로 전환하려면 다음 명령을 입력합니다. `su -`
... 에 나열된 암호를 입력합니다 `Passwords.txt` 파일.
+
루트로 로그인하면 프롬프트가 에서 변경됩니다 `$` 를 선택합니다 `#`.



.. 입력: `*run-host-command ipmitool lan print*` 어플라이언스의 현재 BMC 구성을 표시합니다.


. SG6000-CN 컨트롤러가 제어된 종료를 허용하기에 충분히 작동 중인 경우 link:power-sg6000-cn-controller-off-on.html#shut-down-sg6000-cn-controller["SG6000-CN 컨트롤러를 종료합니다"].
. 이 StorageGRID 어플라이언스의 네트워크 인터페이스 중 DHCP를 사용하도록 구성된 경우 교체 어플라이언스의 MAC 주소를 참조하도록 DHCP 서버의 영구 DHCP 임대 할당을 업데이트해야 할 수 있습니다. 업데이트는 어플라이언스에 예상 IP 주소가 할당되도록 합니다. 을 참조하십시오 link:../commonhardware/locate-mac-address.html["MAC 주소 참조를 업데이트합니다"].
. SG6000-CN 컨트롤러 분리 및 교체:
+
.. 케이블에 레이블을 지정한 다음 케이블과 모든 SFP+ 또는 SFP28 트랜시버를 분리합니다.
+

NOTE: 성능 저하를 방지하려면 케이블을 비틀거나 접거나 끼거나 밟지 마십시오.

.. 캐비닛 또는 랙에서 장애가 발생한 컨트롤러를 분리합니다.
.. 캐비닛 또는 랙에 교체용 컨트롤러를 설치합니다.
.. 케이블 및 SFP+ 또는 SFP28 트랜시버를 교체합니다.
.. 컨트롤러 및 의 전원을 켭니다 link:../installconfig/viewing-status-indicators.html["컨트롤러 LED를 모니터링합니다"] 및 link:../installconfig/troubleshooting-hardware-installation.html#view-boot-codes["부팅 코드"].
+
컨트롤러가 시작되면 컨트롤러 및 어플라이언스 구성 요소에 대한 보류 중인 업데이트가 자동으로 설치됩니다. 이러한 업데이트 설치를 완료하는 데 1시간 이상 걸릴 수 있으며 컨트롤러는 여러 번 재부팅될 수 있습니다.

+

CAUTION: 펌웨어 업데이트 도중 _NOT_인 것으로 확신할 수 없는 경우 어플라이언스를 수동으로 재부팅하지 마십시오.

+
를 연결할 수 있습니다 link:../installconfig/troubleshooting-hardware-installation.html["모니터링"] 또는 link:../installconfig/accessing-storagegrid-appliance-installer.html["서비스 노트북"] SG6000-CN 컨트롤러에 연결하여 업데이트 설치 진행률을 모니터링합니다.

+

NOTE: 설치 프로세스의 일부 단계에서는 서비스 랩톱 연결을 사용할 수 없습니다.



. 컨트롤러를 교체한 어플라이언스에서 KMS(키 관리 서버)를 사용하여 데이터를 암호화한 경우 노드를 그리드에 가입하기 전에 추가 구성이 필요할 수 있습니다. 노드가 그리드에 자동으로 연결되지 않는 경우, 이러한 구성 설정이 새 컨트롤러로 전송되었는지 확인하고 필요한 구성이 없는 설정을 수동으로 구성합니다.
+
** link:../installconfig/configuring-network-links.html["네트워크 링크를 구성합니다"]
** link:../installconfig/setting-ip-configuration.html["StorageGRID IP 주소를 구성합니다"]
** https://docs.netapp.com/us-en/storagegrid/admin/kms-overview-of-kms-and-appliance-configuration.html#set-up-the-appliance["어플라이언스에 대한 노드 암호화를 구성합니다"^]


. 교체한 컨트롤러를 사용하여 어플라이언스에 로그인합니다.
+
.. 다음 명령을 입력합니다. `ssh admin@_grid_node_IP_`
.. 에 나열된 암호를 입력합니다 `Passwords.txt` 파일.
.. 루트로 전환하려면 다음 명령을 입력합니다. `su -`
.. 에 나열된 암호를 입력합니다 `Passwords.txt` 파일.


. 어플라이언스에 대한 BMC 네트워크 연결을 복구합니다. 두 가지 옵션이 있습니다.
+
** 고정 IP, 넷마스크 및 게이트웨이를 사용합니다
** DHCP를 사용하여 IP, 넷마스크 및 게이트웨이를 얻습니다
+
... 정적 IP, 넷마스크 및 게이트웨이를 사용하도록 BMC 구성을 복원하려면 다음 명령을 입력합니다.
+
`*run-host-command ipmitool lan set 1 ipsrc static*`

+
`*run-host-command ipmitool lan set 1 ipaddr _Appliance_IP_*`

+
`*run-host-command ipmitool lan set 1 netmask _Netmask_IP_*`

+
`*run-host-command ipmitool lan set 1 defgw ipaddr _Default_gateway_*`

... DHCP를 사용하여 IP, 넷마스크 및 게이트웨이를 가져오도록 BMC 구성을 복원하려면 다음 명령을 입력합니다.
+
`*run-host-command ipmitool lan set 1 ipsrc dhcp*`





. BMC 네트워크 연결을 복원한 후 BMC 인터페이스에 연결하여 추가 사용자 정의 BMC 구성을 감사하고 복원합니다. 예를 들어, SNMP 트랩 대상 및 e-메일 알림에 대한 설정을 확인해야 합니다. 을 참조하십시오 link:../installconfig/configuring-bmc-interface.html["BMC 인터페이스를 구성합니다"].
. 어플라이언스 노드가 그리드 관리자에 표시되고 경고가 나타나지 않는지 확인합니다.


부품을 교체한 후 키트와 함께 제공된 RMA 지침에 따라 오류가 발생한 부품을 NetApp에 반환합니다. 를 참조하십시오 https://mysupport.netapp.com/site/info/rma["부품 반납 및 교체"^] 페이지를 참조하십시오.

.관련 정보
* link:../installconfig/sg6000-cn-installing-into-cabinet-or-rack.html["SG6000-CN을 캐비닛 또는 랙에 설치합니다"]
* link:../installconfig/viewing-status-indicators.html["상태 표시기를 봅니다"]
* link:../installconfig/troubleshooting-hardware-installation.html#view-boot-codes["SG6000-CN 컨트롤러의 부팅 코드를 봅니다"]

