---
permalink: sg6000/upgrading-santricity-os-on-storage-controllers.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, controller, storage controller, upgrade, upgrading, SANtricity OS, SANtricity 
summary: 스토리지 컨트롤러가 최적의 상태로 작동하도록 하려면 StorageGRID 어플라이언스에 적합한 SANtricity OS의 최신 유지 관리 릴리즈로 업그레이드해야 합니다. 
---
= SG6000 스토리지 컨트롤러에서 SANtricity OS를 업그레이드합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 컨트롤러가 최적의 상태로 작동하도록 하려면 StorageGRID 어플라이언스에 적합한 SANtricity OS의 최신 유지 관리 릴리즈로 업그레이드해야 합니다.

을 참조하십시오 https://imt.netapp.com/matrix/#welcome["NetApp 상호 운용성 매트릭스 툴(IMT)"^] 사용할 버전을 확인합니다.

에서 새 SANtricity OS 소프트웨어 파일을 다운로드합니다 https://mysupport.netapp.com/site/products/all/details/storagegrid-appliance/downloads-tab["NetApp 다운로드: StorageGRID 어플라이언스"^].

현재 설치된 SANtricity OS 버전에 따라 다음 절차 중 하나를 사용하십시오.

* 스토리지 컨트롤러가 SANtricity OS 08.42.20.00(11.42) 이상을 사용하는 경우 그리드 관리자를 사용하여 업그레이드를 수행합니다.
+
link:upgrading-santricity-os-on-storage-controllers-using-grid-manager-sg6000.html["그리드 관리자를 사용하여 스토리지 컨트롤러의 SANtricity OS를 업그레이드합니다"]

* 스토리지 컨트롤러가 08.42.20.00(11.42) 이전의 SANtricity OS 버전을 사용하는 경우 유지보수 모드를 사용하여 업그레이드를 수행합니다.
+
link:upgrading-santricity-os-on-storage-controllers-using-maintenance-mode-sg6000.html["유지보수 모드를 사용하여 스토리지 컨트롤러에서 SANtricity OS를 업그레이드합니다"]




CAUTION: 스토리지 어플라이언스에 대한 SANtricity OS를 업그레이드할 때는 StorageGRID 설명서의 지침을 따라야 합니다. 다른 지침을 사용하면 제품이 작동하지 않을 수 있습니다.
