---
sidebar: sidebar 
permalink: whats-new-appliances.html 
keywords: storagegrid, appliance, whats new 
summary: 이 문서 사이트의 새로운 기능에 대해 알아봅니다. 
---
= StorageGRID 어플라이언스의 새로운 기능
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
StorageGRID 어플라이언스의 새로운 기능을 알아보세요.



== IP 주소 없이도 클라이언트 네트워크를 구성할 수 있습니다.

이제 IP 주소를 지정하지 않고도 클라이언트 네트워크를 활성화할 수 있습니다.  이를 통해 클라이언트 네트워크는 인터페이스 자체에 대한 추가 IP 주소가 필요 없이 StorageGRID 에 VLAN 인터페이스를 구성할 수 있습니다. link:.//installconfig/setting-ip-configuration.html["StorageGRID IP 주소를 구성합니다"] .



== StorageGRID 소프트웨어 및 Appliance Installer의 버전 번호가 정렬되었습니다.

StorgeGRID 버전 12.0의 경우 StorageGRID Appliance Installer의 버전 번호는 StorageGRID 소프트웨어 버전과 일치합니다.  사용자는 더 이상 어떤 버전이 서로 어울리는지 알아낼 필요가 없습니다. link:./installconfig/verifying-and-upgrading-storagegrid-appliance-installer-version.html["StorageGRID 어플라이언스 설치 프로그램 버전을 확인하고 업그레이드합니다"] .



== BMC 정보입니다

StorageGRID 어플라이언스 BMC 인터페이스 사용에 대한 자세한 정보를 이제 사용할 수 있습니다. link:./commonhardware/use-bmc.html["StorageGRID 어플라이언스의 베이스보드 관리 컨트롤러(BMC) 사용"] .



== SG5812 및 SG5860 어플라이언스

StorageGRID SG5812 및 SG5860 어플라이언스는 StorageGRID 그리드에서 스토리지 노드로 작동하는 통합 스토리지 및 컴퓨팅 플랫폼입니다.  를 참조하세요link:./installconfig/hardware-description-sg5800.html["SG5800 어플라이언스: 개요"] 자세히 알아보려면.



== SG6160 어플라이언스

새로운 StorageGRID SG6160 어플라이언스에는 컴퓨팅 컨트롤러와 스토리지 컨트롤러 쉘프가 포함되어 있으며, 스토리지 컨트롤러 쉘프에는 스토리지 컨트롤러 2개와 드라이브 60개, 캐싱을 위한 NVMe SSD 드라이브 2개가 포함됩니다.  선택적으로 SG6160에 60개 드라이브 확장 선반을 추가할 수 있습니다.  참조하다link:./installconfig/hardware-description-sg6100.html["SGF6100 어플라이언스: 개요"] 자세히 알아보려면.



== SG110 및 SG1100 서비스 어플라이언스

새로운 StorageGRID SG110 및 SG1100 서비스 어플라이언스는 향상된 관리 및 부하 분산 성능을 제공하는 혁신적인 하드웨어 업데이트입니다. link:./installconfig/hardware-description-sg110-and-1100.html["SG110 및 SG1100 서비스 어플라이언스: 개요"] .
