---
permalink: installconfig/automating-configuration-of-storagegrid.html 
sidebar: sidebar 
keywords: automate, automating, automation, automatic, configuration, configure 
summary: 그리드 노드를 설치하고 구성한 후 StorageGRID 시스템의 구성을 자동화할 수 있습니다. 
---
= StorageGRID 구성 자동화
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
그리드 노드를 설치하고 구성한 후 StorageGRID 시스템의 구성을 자동화할 수 있습니다.

.시작하기 전에
* 설치 아카이브에서 다음 파일의 위치를 알고 있습니다.
+
[cols="1a,1a"]
|===
| 파일 이름 | 설명 


| configure-storagegrid.py  a| 
구성을 자동화하는 데 사용되는 Python 스크립트입니다



| configure -StorageGrid.sample.json  a| 
스크립트와 함께 사용할 예제 구성 파일



| configure -StorageGrid.blank.json을 지정합니다  a| 
스크립트에 사용할 빈 구성 파일입니다

|===
* 을(를) 만들었습니다 `configure-storagegrid.json` 구성 파일. 이 파일을 작성하려면 예제 구성 파일을 수정할 수 있습니다 (`configure-storagegrid.sample.json`) 또는 빈 구성 파일 (`configure-storagegrid.blank.json`)를 클릭합니다.



CAUTION: 수정된 암호 섹션에서 관리 암호와 프로비저닝 암호를 저장합니다. `configure-storagegrid.json` 구성 파일을 안전한 위치에 보관하세요.  이러한 비밀번호는 설치, 확장 및 유지 관리 절차에 필요합니다.  수정된 내용도 백업해야 합니다. `configure-storagegrid.json` 구성 파일을 만들어 안전한 위치에 저장하세요.

.이 작업에 대해
를 사용할 수 있습니다 `configure-storagegrid.py` Python 스크립트와 `configure-storagegrid.json` StorageGRID 시스템 구성을 자동화하는 구성 파일입니다.


NOTE: 또는 를 사용하여 시스템을 구성할 수도 https://docs.netapp.com/us-en/storagegrid/primer/exploring-grid-manager.html["그리드 관리자"^]link:overview-of-installation-rest-apis.html["설치 API"] 있습니다.

.단계
. Python 스크립트를 실행하기 위해 사용 중인 Linux 시스템에 로그인합니다.
. 설치 아카이브를 추출한 디렉토리로 변경합니다.
+
예: +
`cd StorageGRID-Webscale-_version/platform_`

+
위치 `_platform_` 있습니다 `debs`, `rpms`, 또는 `vsphere`.

. Python 스크립트를 실행하고 생성한 구성 파일을 사용합니다.
+
예를 들면 다음과 같습니다.

+
[listing]
----
./configure-storagegrid.py ./configure-storagegrid.json --start-install
----


.작업을 마친 후
복구 패키지 `.zip` 파일은 구성 프로세스 중에 생성되며 설치 및 구성 프로세스를 실행 중인 디렉토리에 다운로드됩니다. 하나 이상의 그리드 노드에 장애가 발생할 경우 StorageGRID 시스템을 복구할 수 있도록 복구 패키지 파일을 백업해야 합니다. 예를 들어, 안전한 백업 네트워크 위치 및 안전한 클라우드 저장소 위치에 복사합니다.


CAUTION: 복구 패키지 파일은 StorageGRID 시스템에서 데이터를 가져오는 데 사용할 수 있는 암호화 키와 암호가 포함되어 있으므로 보안을 유지해야 합니다.

임의 암호를 생성해야 한다고 지정한 경우 의 압축을 풀어야 합니다 `Passwords.txt` 파일을 만들고 StorageGRID 시스템에 액세스하는 데 필요한 암호를 찾습니다.

[listing]
----
######################################################################
##### The StorageGRID "recovery package" has been downloaded as: #####
#####           ./sgws-recovery-package-994078-rev1.zip          #####
#####   Safeguard this file as it will be needed in case of a    #####
#####                 StorageGRID node recovery.                 #####
######################################################################
----
확인 메시지가 표시되면 StorageGRID 시스템이 설치 및 구성됩니다.

[listing]
----
StorageGRID has been configured and installed.
----