---
permalink: installconfig/deploying-appliance-storage-node.html 
sidebar: sidebar 
keywords: storage node, storage appliance, deploy node, deploying node, node, deploy, deploying 
summary: 스토리지 어플라이언스를 설치 및 구성한 후 StorageGRID 시스템에서 스토리지 노드로 구축할 수 있습니다. 어플라이언스를 스토리지 노드로 배포할 때는 어플라이언스에 포함된 StorageGRID 어플라이언스 설치 프로그램을 사용합니다. 
---
= 어플라이언스 스토리지 노드 구축
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 어플라이언스를 설치 및 구성한 후 StorageGRID 시스템에서 스토리지 노드로 구축할 수 있습니다. 어플라이언스를 스토리지 노드로 배포할 때는 어플라이언스에 포함된 StorageGRID 어플라이언스 설치 프로그램을 사용합니다.

.시작하기 전에
* 어플라이언스 노드를 클론 생성하는 경우 를 계속 수행합니다 link:../commonhardware/appliance-node-cloning-procedure.html["어플라이언스 노드 클론 복제"] 프로세스.
* 이 제품은 랙 또는 캐비닛에 설치되었고 네트워크에 연결되어 있으며 전원이 켜져 있습니다.
* StorageGRID 어플라이언스 설치 프로그램을 사용하여 어플라이언스에 대해 네트워크 링크, IP 주소 및 포트 재매핑(필요한 경우)이 구성되었습니다.
* 어플라이언스의 컴퓨팅 컨트롤러에 할당된 IP 주소 중 하나를 알고 있습니다. 연결된 모든 StorageGRID 네트워크에 대해 IP 주소를 사용할 수 있습니다.
* StorageGRID 시스템의 기본 관리 노드가 배포되었습니다.
* StorageGRID 어플라이언스 설치 프로그램의 IP 구성 페이지에 나열된 모든 그리드 네트워크 서브넷은 기본 관리 노드의 그리드 네트워크 서브넷 목록에 정의되어 있습니다.
* 지원되는 웹 브라우저가 있는 서비스 랩톱이 있습니다.


.이 작업에 대해
각 스토리지 어플라이언스는 단일 스토리지 노드로 작동합니다. 모든 어플라이언스는 그리드 네트워크, 관리 네트워크 및 클라이언트 네트워크에 연결할 수 있습니다

어플라이언스 스토리지 노드를 StorageGRID 시스템에 배포하려면 StorageGRID 어플라이언스 설치 프로그램에 액세스하여 다음 단계를 수행합니다.

* 운영 관리 노드의 IP 주소와 스토리지 노드의 이름을 지정하거나 확인합니다.
* 구축을 시작하고 볼륨이 구성되고 소프트웨어가 설치될 때까지 기다립니다.
* 어플라이언스 설치 작업이 중간에 일시 중지되면 그리드 관리자에 로그인하고 모든 그리드 노드를 승인하고 StorageGRID 설치 및 배포 프로세스를 완료하여 설치를 다시 시작합니다.



NOTE: 한 번에 여러 어플라이언스 노드를 배포해야 하는 경우 다음 링크를 사용하여 설치 프로세스를 자동화할 수 있습니다.../installconfig/automating-appliance-installation-and-configuration.html#automate-with-configure-sga-py-script[`configure-sga.py` 장치 설치 스크립트].

* 확장 또는 복구 작업을 수행하는 경우 해당 지침을 따르십시오.
+
** 기존 StorageGRID 시스템에 어플라이언스 스토리지 노드를 추가하려면 의 지침을 참조하십시오 https://docs.netapp.com/us-en/storagegrid/expand/adding-grid-nodes-to-existing-site-or-adding-new-site.html["그리드 노드 추가"^].
** 복구 작업의 일부로 어플라이언스 스토리지 노드를 배포하려면 지침을 참조하십시오. https://docs.netapp.com/us-en/storagegrid/maintain/recovering-storagegrid-appliance-storage-node.html["어플라이언스 스토리지 노드 복구"^]




.단계
. 브라우저를 열고 어플라이언스의 컴퓨팅 컨트롤러에 대한 IP 주소 중 하나를 입력합니다. 를 누릅니다
`*https://_Controller_IP_:8443*`
+
StorageGRID 어플라이언스 설치 관리자 홈 페이지가 나타납니다.

. 노드 유형 * 을 선택합니다. 자세한 내용은 을 https://docs.netapp.com/us-en/storagegrid/primer/what-storage-node-is.html#types-of-storage-nodes["스토리지 노드 유형"]참조하십시오.
+

NOTE: 메타데이터 전용은 어플라이언스 배포 중에만 선택할 수 있습니다. 메타데이터 전용을 스토리지 노드 유형으로 선택한 경우 어플라이언스가 구축된 후에는 변경할 수 없습니다.

. 노드 이름 * 필드에 이 어플라이언스 노드에 사용할 시스템 이름을 입력하고 * 저장 * 을 클릭합니다.
+
여기에 표시되는 이름은 어플라이언스 노드의 시스템 이름입니다. 시스템 이름은 내부 StorageGRID 작업에 필요하며 변경할 수 없습니다.

. Primary Admin Node connection * 섹션에서 Primary Admin Node의 IP 주소를 지정해야 하는지 여부를 확인합니다.
+
이전에 이 데이터 센터에 다른 노드를 설치한 경우 StorageGRID 어플라이언스 설치 관리자는 기본 관리 노드 또는 admin_IP가 구성된 다른 그리드 노드가 동일한 서브넷에 있다고 가정하여 이 IP 주소를 자동으로 검색할 수 있습니다.

. 이 IP 주소가 표시되지 않거나 변경해야 하는 경우 주소를 지정합니다.
+
[cols="1a,2a"]
|===
| 옵션을 선택합니다 | 설명 


 a| 
수동 IP 입력
 a| 
.. 관리자 노드 검색 활성화 * 확인란의 선택을 취소합니다.
.. IP 주소를 수동으로 입력합니다.
.. 저장 * 을 클릭합니다.
.. 새 IP 주소가 준비될 때까지 연결 상태를 기다립니다.




 a| 
연결된 모든 운영 관리 노드의 자동 검색
 a| 
.. 관리자 노드 검색 활성화 * 확인란을 선택합니다.
.. 검색된 IP 주소 목록이 표시될 때까지 기다립니다.
.. 이 어플라이언스 스토리지 노드를 구축할 그리드의 기본 관리 노드를 선택합니다.
.. 저장 * 을 클릭합니다.
.. 새 IP 주소가 준비될 때까지 연결 상태를 기다립니다.


|===
. 설치 * 섹션에서 현재 상태가 "설치 시작 준비 완료"인지 확인합니다 `_node name_` 기본 관리 노드가 있는 그리드로 `_admin_ip_` "및 * 설치 시작 * 버튼이 활성화되어 있습니다.
+
설치 시작 * 버튼이 활성화되지 않은 경우 네트워크 구성 또는 포트 설정을 변경해야 할 수 있습니다. 자세한 내용은 제품의 유지보수 지침을 참조하십시오.

+

NOTE: 스토리지 노드 어플라이언스를 노드 클론 생성 타겟으로 구축하는 경우 여기에서 구축 프로세스를 중지하고 를 계속하십시오
link:../commonhardware/appliance-node-cloning-procedure.html["노드 클론 생성 절차"].

. StorageGRID 어플라이언스 설치 관리자 홈 페이지에서 * 설치 시작 * 을 클릭합니다.
+
현재 상태가 ""Installation is in progress(설치 진행 중)", 및 로 변경됩니다 link:../installconfig/monitoring-appliance-installation.html["모니터 설치 페이지"] 가 표시됩니다.

+

NOTE: 모니터 설치 페이지에 수동으로 액세스해야 하는 경우 * 모니터 설치 * 를 클릭합니다.

. 그리드에 여러 어플라이언스 스토리지 노드가 포함된 경우 각 어플라이언스에 대해 이 단계를 반복합니다.
+

NOTE: 한 번에 여러 어플라이언스 스토리지 노드를 배포해야 하는 경우 다음 링크를 사용하여 설치 프로세스를 자동화할 수 있습니다../installconfig/automating-appliance-installation-and-configuration.html# automate-with-configure-sga-py-script[`configure-sga.py` 장치 설치 스크립트].


