---
permalink: installconfig/optional-changing-raid-mode.html 
sidebar: sidebar 
keywords: storage node, storage appliance, raid, raid mode, change, changing, modify, DDP, ddp16, RAID 6 
summary: 일부 어플라이언스 모델에서는 스토리지 및 복구 요구 사항을 수용하기 위해 어플라이언스에서 다른 RAID 모드로 변경할 수 있습니다. 어플라이언스 스토리지 노드를 구축하기 전에만 모드를 변경할 수 있습니다. 
---
= 선택 사항: RAID 모드 변경(SG5760, SG5860, SG6000 및 SG6160)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
일부 어플라이언스 모델에서는 스토리지 및 복구 요구 사항을 수용하기 위해 어플라이언스에서 다른 RAID 모드로 변경할 수 있습니다. 어플라이언스 스토리지 노드를 구축하기 전에만 모드를 변경할 수 있습니다.

ConfigBuilder를 사용하여 JSON 파일을 생성하는 경우 RAID 모드를 자동으로 변경할 수 있습니다. 을 참조하십시오 link:automating-appliance-installation-and-configuration.html["어플라이언스 설치 및 구성 자동화"].

.이 작업에 대해
어플라이언스가 지원하는 경우 다음 볼륨 구성 옵션 중 하나를 선택할 수 있습니다.


NOTE: 볼륨 크기가 모든 DDP 및 RAID 유형에서 일관되지 않습니다. DDP 및 RAID6의 작동 방식이 다르면 볼륨 크기가 달라집니다.

* * DDP(동적 디스크 풀) *: 이 모드는 데이터 드라이브 8개마다 2개의 패리티 드라이브를 사용합니다. 모든 어플라이언스에 대한 기본 권장 모드입니다.
+
** DDP는 RAID 6과 비교하여 시스템 성능을 향상하고, 드라이브 장애 후 리빌드 시간을 줄이고, 관리를 간소화합니다.
** 스토리지 어플라이언스 또는 확장 쉘프당 하나의 디스크 풀이 생성됩니다.
** DDP는 SG5760, SG5860 및 SG6160 어플라이언스에서 드로어 손실 보호를 제공합니다.
+

NOTE: DDP는 두 개의 SSD로 인해 SG6060 어플라이언스에는 드로어 손실 보호를 제공하지 않습니다. SG6060에 추가된 확장 쉘프에서는 서랍 손실 보호를 효과적으로 수행합니다.



* * DDP16 *: 이 모드는 데이터 드라이브 16개마다 2개의 패리티 드라이브를 사용하므로 DDP에 비해 스토리지 효율성이 높습니다.
+
** RAID 6에 비해 DDP16은 향상된 시스템 성능, 드라이브 장애 후 재구축 시간 단축, 관리 용이성 및 스토리지 효율성을 제공합니다.
** DDP16 모드를 사용하려면 저장 장치에 최소 20개의 드라이브가 있어야 합니다.
** 스토리지 어플라이언스 또는 확장 쉘프당 하나의 디스크 풀이 생성됩니다.
** DDP16은 드로어 손실 방지 기능을 제공하지 않습니다.


* * RAID6 *: 이 모드는 16개 이상의 데이터 드라이브마다 2개의 패리티 드라이브를 사용합니다. 각 디스크의 패리티 스트라이프를 사용하는 하드웨어 보호 구성표로, 데이터가 손실되기 전에 RAID 세트 내에서 2개의 디스크 장애를 허용합니다. RAID 6 모드를 사용하려면 구성에 최소 20개의 드라이브가 포함되어 있어야 합니다. RAID 6은 DDP와 비교할 때 어플라이언스의 스토리지 효율성을 높일 수 있지만 대부분의 StorageGRID 환경에서는 권장되지 않습니다.
+
** RAID 6는 확장 쉘프당 하나의 글로벌 핫 스페어를 제공합니다. 예를 들어, 확장 쉘프가 2개인 SG6160에는 핫 스페어 3개가 있습니다.
** 60-드라이브 스토리지 어플라이언스에서 StorageGRID은 3개의 볼륨 그룹을 생성합니다. 각 그룹은 최소 18개 드라이브(16+2), 최대 21개 드라이브(19+2).
** SGF6024에서 RAID 6 볼륨 그룹은 핫 스페어 1개를 포함하는 23개의 드라이브로 구성됩니다.
** RAID 6 볼륨은 약간 더 크므로 DDP16에서 노드를 복제할 수 있는 경우가 많습니다. RAID 6 구성의 볼륨 크기는 볼륨 그룹마다 다를 수 있습니다.





CAUTION: 볼륨이 이미 구성되었거나 StorageGRID가 이전에 설치된 경우 RAID 모드를 변경하면 볼륨이 제거되고 교체됩니다. 해당 볼륨의 모든 데이터가 손실됩니다.

[role="tabbed-block"]
====
.SG5760입니다
--
.시작하기 전에
* 드라이브가 60개인 SG5760을 사용하는 경우 SG5712를 사용하는 경우 기본 DDP 모드를 사용해야 합니다.
* StorageGRID에 연결할 수 있는 모든 클라이언트를 사용 중입니다.
* 클라이언트에는 가 https://docs.netapp.com/us-en/storagegrid/admin/web-browser-requirements.html["지원되는 웹 브라우저"^]있습니다.


.단계
. 서비스 랩톱을 사용하여 웹 브라우저를 열고 StorageGRID 어플라이언스 설치 프로그램:+ 에 액세스합니다
`*https://_E5700SG_Controller_IP_:8443*`
+
위치 `_E5700SG_Controller_IP_` 은(는) E5500SG 컨트롤러의 IP 주소입니다.

. 고급 * > * RAID 모드 * 를 선택합니다.
. RAID 모드 구성 * 페이지의 모드 드롭다운 목록에서 원하는 RAID 모드를 선택합니다.
. 저장 * 을 클릭합니다.


--
.SG5860
--
.시작하기 전에
* 60개의 드라이브가 있는 SG5860이 있습니다. SG5812가 있는 경우 기본 DDP 모드를 사용해야 합니다.
* StorageGRID에 연결할 수 있는 모든 클라이언트를 사용 중입니다.
* 클라이언트에는 가 https://docs.netapp.com/us-en/storagegrid/admin/web-browser-requirements.html["지원되는 웹 브라우저"^]있습니다.


.단계
. 서비스 랩톱을 사용하여 웹 브라우저를 열고 StorageGRID 어플라이언스 설치 프로그램:+ 에 액세스합니다
`*https://_SG5800_Controller_IP_:8443*`
+
위치 `_SG5800_Controller_IP_` 는 SG5800 컨트롤러의 IP 주소입니다.

. 고급 * > * RAID 모드 * 를 선택합니다.
. RAID 모드 구성 * 페이지의 모드 드롭다운 목록에서 원하는 RAID 모드를 선택합니다.
. 저장 * 을 클릭합니다.


--
.SG6000 을 참조하십시오
--
.시작하기 전에
* StorageGRID에 연결할 수 있는 모든 클라이언트를 사용 중입니다.
* 클라이언트에는 가  https://docs.netapp.com/us-en/storagegrid/admin/web-browser-requirements.html["지원되는 웹 브라우저"^]있습니다.


.단계
. 브라우저를 열고 어플라이언스의 컴퓨팅 컨트롤러에 대한 IP 주소 중 하나를 입력합니다.
+
`*https://_Controller_IP_:8443*`

+
`_Controller_IP_` 는 3개의 StorageGRID 네트워크 중 하나에 있는 컴퓨팅 컨트롤러(스토리지 컨트롤러가 아님)의 IP 주소입니다.

+
StorageGRID 어플라이언스 설치 관리자 홈 페이지가 나타납니다.

. 고급 * > * RAID 모드 * 를 선택합니다.
. RAID 모드 구성 * 페이지의 모드 드롭다운 목록에서 원하는 RAID 모드를 선택합니다.
. 저장 * 을 클릭합니다.


--
.SG6160
--
.시작하기 전에
* StorageGRID에 연결할 수 있는 모든 클라이언트를 사용 중입니다.
* 클라이언트에는 가  https://docs.netapp.com/us-en/storagegrid/admin/web-browser-requirements.html["지원되는 웹 브라우저"^]있습니다.


.단계
. 브라우저를 열고 어플라이언스의 컴퓨팅 컨트롤러에 대한 IP 주소 중 하나를 입력합니다.
+
`*https://_Controller_IP_:8443*`

+
`_Controller_IP_` 는 3개의 StorageGRID 네트워크 중 하나에 있는 컴퓨팅 컨트롤러(스토리지 컨트롤러가 아님)의 IP 주소입니다.

+
StorageGRID 어플라이언스 설치 관리자 홈 페이지가 나타납니다.

. 고급 * > * RAID 모드 * 를 선택합니다.
. RAID 모드 구성 * 페이지의 모드 드롭다운 목록에서 원하는 RAID 모드를 선택합니다.
. 저장 * 을 클릭합니다.


--
====