---
permalink: installconfig/overview-of-installation-rest-apis.html 
sidebar: sidebar 
keywords: installation REST API, REST API, installation REST APIs, REST APIs, Appliance Installer API, Appliance Installer APIs, Install API, Install APIs, Installer API, Installer APIs, Installation API, Installation APIs, api, apis 
summary: StorageGRID는 설치 작업을 수행하기 위한 두 가지 REST API, 즉 StorageGRID 설치 API와 StorageGRID 어플라이언스 설치 관리자 API를 제공합니다. 
---
= REST API 설치 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID는 설치 작업을 수행하기 위한 두 가지 REST API, 즉 StorageGRID 설치 API와 StorageGRID 어플라이언스 설치 관리자 API를 제공합니다.

두 API 모두 Swagger 오픈 소스 API 플랫폼을 사용하여 API 문서를 제공합니다. swagger를 사용하면 개발자와 개발자가 아닌 사용자가 API가 매개 변수 및 옵션에 어떻게 응답하는지 보여주는 사용자 인터페이스에서 API와 상호 작용할 수 있습니다. 이 문서에서는 표준 웹 기술 및 JSON 데이터 형식에 대해 잘 알고 있다고 가정합니다.


CAUTION: API Docs 웹 페이지를 사용하여 수행하는 모든 API 작업은 라이브 작업입니다. 실수로 구성 데이터나 기타 데이터를 작성, 업데이트 또는 삭제하지 않도록 주의하십시오.

각 REST API 명령에는 API의 URL, HTTP 작업, 필수 또는 선택적 URL 매개 변수, 그리고 예상되는 API 응답이 포함됩니다.



== StorageGRID 설치 API

StorageGRID 설치 API는 StorageGRID 시스템을 처음 구성할 때와 기본 관리자 노드 복구를 수행해야 하는 경우에만 사용할 수 있습니다. 설치 API는 Grid Manager에서 HTTPS를 통해 액세스할 수 있습니다.

API 설명서에 액세스하려면 기본 관리 노드의 설치 웹 페이지로 이동하여 메뉴 모음에서 * 도움말 * > * API 설명서 * 를 선택합니다.

StorageGRID 설치 API에는 다음 섹션이 포함되어 있습니다.

* * config *: 제품 릴리스 및 API 버전과 관련된 작업. 제품 릴리스 버전과 해당 릴리스에서 지원하는 API의 주요 버전을 나열할 수 있습니다.
* * 그리드 *: 그리드 레벨 구성 작업. 그리드 세부 정보, 그리드 네트워크 서브넷, 그리드 암호, NTP 및 DNS 서버 IP 주소를 포함한 그리드 설정을 얻고 업데이트할 수 있습니다.
* * 노드 *: 노드 레벨 구성 작업 그리드 노드 목록을 검색하고, 그리드 노드를 삭제하고, 그리드 노드를 구성하고, 그리드 노드를 보고, 그리드 노드의 구성을 재설정할 수 있습니다.
* * 프로비저닝 *: 프로비저닝 작업. 프로비저닝 작업을 시작하고 프로비저닝 작업의 상태를 볼 수 있습니다.
* * 복구 *: 기본 관리자 노드 복구 작업 정보를 재설정하고, 복구 패키지를 업로드하고, 복구를 시작하고, 복구 작업의 상태를 볼 수 있습니다.
* * recovery-package *: 복구 패키지를 다운로드하기 위한 작업.
* * 사이트 *: 사이트 레벨 구성 작업 사이트를 만들고, 보고, 삭제하고, 수정할 수 있습니다.




== StorageGRID 어플라이언스 설치 관리자 API입니다

StorageGRID 어플라이언스 설치 관리자 API는 에서 HTTPS를 통해 액세스할 수 있습니다 `_Controller_IP_:8443`.

API 설명서에 액세스하려면 어플라이언스의 StorageGRID 어플라이언스 설치 프로그램으로 이동하여 메뉴 모음에서 * 도움말 * > * API Docs * 를 선택합니다.

StorageGRID 어플라이언스 설치 관리자 API에는 다음 섹션이 포함되어 있습니다.

* * 클론 *: 노드 클론 생성을 구성 및 제어하는 작업.
* * 암호화 *: 암호화를 관리하고 암호화 상태를 볼 수 있는 작업.
* * 하드웨어 구성 *: 연결된 하드웨어에서 시스템 설정을 구성하는 작업.
* * 설치 *: 어플라이언스 설치 시작 및 설치 상태 모니터링을 위한 작업.
* * 네트워킹 *: StorageGRID 어플라이언스 및 어플라이언스 포트 설정에 대한 그리드, 관리자 및 클라이언트 네트워크 구성과 관련된 작업.
* * setup *: 시스템에 대한 정보를 얻고 기본 관리 노드 IP를 업데이트하는 요청을 포함하여 초기 어플라이언스 설치 설정에 도움이 되는 작업.
* * 지원 *: 컨트롤러를 재부팅하고 로그를 가져오는 작업
* * update-config *: StorageGRID 어플라이언스 구성을 업데이트하는 작업.
* * 업그레이드 *: 어플라이언스 펌웨어 업그레이드와 관련된 작업.
* * 업로그램 *: StorageGRID 설치 파일을 업로드하는 작업.

