---
permalink: installconfig/verifying-and-upgrading-storagegrid-appliance-installer-version.html 
sidebar: sidebar 
keywords: verifying, verify, upgrading, upgrade, update, updating, Appliance Installer, version, release 
summary: 어플라이언스의 StorageGRID 어플라이언스 설치 프로그램 버전은 StorageGRID 시스템에 설치된 소프트웨어 버전과 일치해야 모든 StorageGRID 기능이 지원됩니다. 
---
= StorageGRID 어플라이언스 설치 프로그램 버전을 확인하고 업그레이드합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
어플라이언스의 StorageGRID 어플라이언스 설치 프로그램 버전은 StorageGRID 시스템에 설치된 소프트웨어 버전과 일치해야 모든 StorageGRID 기능이 지원됩니다.

.시작하기 전에
StorageGRID 어플라이언스 설치 프로그램에 액세스했습니다.

.이 작업에 대해
StorageGRID 어플라이언스는 StorageGRID 어플라이언스 설치 프로그램이 사전 설치된 상태로 제공됩니다. 최근에 업그레이드된 StorageGRID 시스템에 어플라이언스를 추가하는 경우 어플라이언스를 새 노드로 설치하기 전에 StorageGRID 어플라이언스 설치 프로그램을 수동으로 업그레이드해야 할 수 있습니다.

새 StorageGRID 버전으로 업그레이드하면 StorageGRID 어플라이언스 설치 프로그램이 자동으로 업그레이드됩니다. 설치된 어플라이언스 노드에서 StorageGRID 어플라이언스 설치 프로그램을 업그레이드할 필요가 없습니다. 이 절차는 이전 버전의 StorageGRID 어플라이언스 설치 프로그램이 포함된 어플라이언스를 설치하는 경우에만 필요합니다.

.단계
. StorageGRID 어플라이언스 설치 프로그램에서 * 고급 * > * 펌웨어 업그레이드 * 를 선택합니다.
. 현재 펌웨어 버전을 StorageGRID 시스템에 설치된 소프트웨어 버전과 비교합니다. (그리드 관리자 상단에서 도움말 아이콘을 선택하고 * 정보 * 를 선택합니다.)
+
두 버전의 두 번째 숫자가 일치해야 합니다. 예를 들어, StorageGRID 시스템에서 버전 11. * 6 *._x_._y_를 실행하는 경우 StorageGRID 어플라이언스 설치 프로그램 버전은 3. * 6 *._z_이어야 합니다.

. 어플라이언스에 StorageGRID 어플라이언스 설치 프로그램의 하위 수준 버전이 있는 경우 로 이동합니다 https://mysupport.netapp.com/site/products/all/details/storagegrid-appliance/downloads-tab["NetApp 다운로드: StorageGRID 어플라이언스"^].
+
NetApp 계정의 사용자 이름과 암호를 사용하여 로그인합니다.

. StorageGRID Appliances*용 * 지원 파일의 적절한 버전과 해당 체크섬 파일을 다운로드하십시오.
+
StorageGRID 어플라이언스에 대한 지원 파일은 입니다 `.zip` 모든 StorageGRID 어플라이언스 모델의 현재 및 이전 펌웨어 버전이 포함된 아카이브

+
StorageGRID 어플라이언스에 대한 지원 파일을 다운로드한 후 의 압축을 풉니다 `.zip` StorageGRID 어플라이언스 설치 프로그램 설치에 대한 중요 정보는 README 파일을 보관하고 참조하십시오.

. StorageGRID 어플라이언스 설치 프로그램의 펌웨어 업그레이드 페이지의 지침에 따라 다음 단계를 수행하십시오.
+
.. 컨트롤러 유형에 적합한 지원 파일(펌웨어 이미지)을 업로드합니다. 일부 펌웨어 버전은 체크섬 파일을 업로드해야 합니다. 체크섬 파일을 묻는 메시지가 표시되면 StorageGRID 어플라이언스에 대한 지원 파일에서도 찾을 수 있습니다.
.. 비활성 파티션을 업그레이드합니다.
.. 재부팅하고 파티션을 바꿉니다.
.. 컨트롤러 유형에 맞는 지원 파일(펌웨어 이미지)을 다시 업로드합니다. 일부 펌웨어 버전은 체크섬 파일을 업로드해야 합니다. 체크섬 파일을 묻는 메시지가 표시되면 StorageGRID 어플라이언스에 대한 지원 파일에서도 찾을 수 있습니다.
.. 두 번째(비활성) 파티션을 업그레이드합니다.




.관련 정보
link:../installconfig/accessing-storagegrid-appliance-installer.html["StorageGRID 어플라이언스 설치 프로그램에 액세스합니다"]
