---
permalink: sg6100/index.html 
sidebar: sidebar 
keywords: storagegrid, sg6100 storage appliance, SGF6112 storage appliance, maintain, maintaining, hardware, procedures, tasks 
summary: 제품에 대한 유지보수 절차를 수행해야 할 수 있습니다. SG6100 어플라이언스 유지 관리에 대한 절차는 이 섹션에 나와 있습니다. 
---
= SG6100 어플라이언스를 유지보수 합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
제품에 대한 유지보수 절차를 수행해야 할 수 있습니다. SG6100 어플라이언스 유지 관리에 대한 절차는 이 섹션에 나와 있습니다.

이 섹션의 절차에서는 어플라이언스가 이미 StorageGRID 시스템의 스토리지 노드로 구축되었다고 가정합니다.

* 유지관리 구성 절차 * 는 어플라이언스 설치 프로그램, 그리드 관리자 또는 BMC 인터페이스를 사용하여 수행됩니다. 이러한 절차에는 다음이 포함됩니다.

* link:turning-sgf6112-identify-led-on-and-off.html["제품 식별 LED를 켜고 끕니다"]
* link:locating-sgf6112-in-data-center.html["데이터 센터에서 어플라이언스를 찾습니다"]
* link:power-sgf6112-off-on.html["제품을 종료하십시오"]
* link:changing-link-configuration-of-sgf6112-appliance.html["어플라이언스의 링크 구성을 변경합니다"]


* 하드웨어 유지보수 절차 * 를 수행하려면 특정 SGF6112 구성 요소를 물리적으로 조작해야 합니다.



== 드라이브 펌웨어의 업그레이드

어플라이언스를 재부팅할 때마다 SGF6112의 드라이브에 있는 펌웨어가 자동으로 확인됩니다. 필요한 경우 펌웨어는 현재 StorageGRID 릴리스에서 예상되는 버전으로 자동 업그레이드됩니다. 일반적으로 StorageGRID 소프트웨어를 업그레이드하는 동안 펌웨어를 업그레이드합니다. 기존 StorageGRID 버전에 필요한 드라이브 펌웨어 업그레이드가 핫픽스에 포함됩니다. 각 핫픽스와 함께 제공된 지침을 따라 업그레이드가 이 핫픽스로 혜택을 받을 수 있는 모든 드라이브에 적용되었는지 확인합니다.


NOTE: SGF6112 어플라이언스를 유지보수하는 데 SANtricity System Manager가 필요하지 않습니다.



== 일반 유지보수 절차

을 참조하십시오 link:../commonhardware/index.html["일반적인 유지보수 절차"] 핫픽스 적용, 노드 또는 사이트 복구, 네트워크 유지 관리 수행 등 모든 어플라이언스에 대해 동일한 절차를 수행합니다.

을 참조하십시오 link:../installconfig/configuring-hardware.html["어플라이언스 하드웨어를 설정합니다"] 최초 어플라이언스 설치 및 구성 중에도 수행되는 어플라이언스 유지보수 절차의 경우
