---
permalink: sg5700/replacing-e5700sg-controller.html 
sidebar: sidebar 
keywords: storagegrid, sg5700, storage node, storage appliance, Replacing, replace, E5700sg, controller, remove, removing, removal, install, installing, installation 
summary: E700SG 컨트롤러가 최적의 상태로 작동하지 않거나 장애가 발생한 경우 교체해야 할 수 있습니다. 
---
= E5700SG 컴퓨팅 컨트롤러를 교체합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
E700SG 컨트롤러가 최적의 상태로 작동하지 않거나 장애가 발생한 경우 교체해야 할 수 있습니다.

.시작하기 전에
* 교체할 컨트롤러와 부품 번호가 동일한 교체 컨트롤러가 있습니다.
* 장애가 발생한 E5700 컨트롤러 교체를 위한 E-Series 지침을 다운로드했습니다.
+

NOTE: 특정 단계를 수행하기 위한 추가 세부 정보가 필요한 경우에만 E-Series 지침을 참조할 수 있습니다. 절차가 동일하지 않으므로 E-Series 지침에 따라 StorageGRID 어플라이언스의 컨트롤러를 교체하지 마십시오. 예를 들어, E5700 컨트롤러의 E-Series 지침은 장애가 발생한 컨트롤러에서 배터리와 호스트 인터페이스 카드(HIC)를 제거하여 교체 컨트롤러에 설치하는 방법을 설명합니다. 이러한 단계는 E5500SG 컨트롤러에는 적용되지 않습니다.

* 컨트롤러에 연결된 각 케이블을 식별하는 라벨이 있습니다.


.이 작업에 대해
컨트롤러를 교체할 때 어플라이언스 스토리지 노드에 액세스할 수 없습니다. E5500SG 컨트롤러가 충분히 작동하는 경우 이 절차를 시작할 때 제어된 종료를 수행할 수 있습니다.


NOTE: StorageGRID 소프트웨어를 설치하기 전에 컨트롤러를 교체하는 경우 이 절차를 완료한 후 즉시 StorageGRID 어플라이언스 설치 프로그램에 액세스하지 못할 수 있습니다. 어플라이언스와 동일한 서브넷에 있는 다른 호스트에서 StorageGRID 어플라이언스 설치 프로그램에 액세스할 수 있지만 다른 서브넷에 있는 호스트에서는 액세스할 수 없습니다. 이 조건은 15분 내에 해결되어야 하며(원래 컨트롤러의 ARP 캐시 항목이 시간 초과될 때), 또는 로컬 라우터 또는 게이트웨이에서 수동으로 이전의 ARP 캐시 항목을 삭제하여 즉시 조건을 지울 수 있습니다.

.단계
. E5500SG 컨트롤러를 종료합니다.
+
.. 그리드 노드에 로그인합니다.
+
... 다음 명령을 입력합니다. `ssh admin@_grid_node_IP_`
... 에 나열된 암호를 입력합니다 `Passwords.txt` 파일.
... 루트로 전환하려면 다음 명령을 입력합니다. `su -`
... 에 나열된 암호를 입력합니다 `Passwords.txt` 파일.
+
루트로 로그인하면 프롬프트가 에서 변경됩니다 `$` 를 선택합니다 `#`.



.. E5500SG 컨트롤러:+ 를 종료합니다
`*shutdown -h now*`
.. 캐시 메모리의 데이터가 드라이브에 기록될 때까지 기다립니다.
+
E2800 컨트롤러 후면의 녹색 캐시 활성 LED는 캐시된 데이터를 드라이브에 기록해야 할 때 켜집니다. 이 LED가 꺼질 때까지 기다려야 합니다.



. 전원을 끕니다.
+
.. SANtricity 시스템 관리자의 홈 페이지에서 * 진행 중인 작업 보기 * 를 선택합니다.
.. 모든 작업이 완료되었는지 확인합니다.
.. 제품의 두 전원 스위치를 모두 끕니다.
.. 모든 LED가 꺼질 때까지 기다립니다.


. 컨트롤러에 연결된 StorageGRID 네트워크가 DHCP 서버를 사용하는 경우:
+
.. 교체용 컨트롤러의 포트에 대한 MAC 주소를 확인합니다(컨트롤러의 레이블에 위치).
.. 네트워크 관리자에게 문의하여 교체 컨트롤러의 MAC 주소를 반영하도록 원본 컨트롤러의 IP 주소 설정을 업데이트하십시오.
+

CAUTION: 교체 컨트롤러에 전원을 켜기 전에 원래 컨트롤러의 IP 주소가 업데이트되었는지 확인해야 합니다. 그렇지 않으면 컨트롤러가 부팅될 때 새 DHCP IP 주소를 가져오며 StorageGRID에 다시 연결되지 않을 수 있습니다. 이 단계는 컨트롤러에 연결된 모든 StorageGRID 네트워크에 적용됩니다.



. 제품에서 컨트롤러를 분리합니다.
+
.. ESD 밴드를 착용하거나 정전기 방지 조치를 취하십시오.
.. 케이블에 레이블을 지정한 다음 케이블 및 SFP를 분리합니다.
+

NOTE: 성능 저하를 방지하려면 케이블을 비틀거나 접거나 끼거나 밟지 마십시오.

.. 캠 핸들의 래치를 눌러 제품에서 컨트롤러를 분리한 다음 캠 핸들을 오른쪽으로 엽니다.
.. 양손과 캠 손잡이를 사용하여 제어기를 제품에서 밀어 꺼냅니다.
+

CAUTION: 컨트롤러의 무게를 지탱하려면 항상 두 손을 사용하십시오.



. 교체 컨트롤러를 제품에 설치합니다.
+
.. 이동식 덮개가 아래를 향하도록 컨트롤러를 뒤집습니다.
.. 캠 손잡이를 열린 상태에서 컨트롤러를 제품 안으로 끝까지 밀어 넣습니다.
.. 캠 핸들을 왼쪽으로 이동하여 컨트롤러를 제자리에 고정합니다.
.. 케이블 및 SFP를 교체합니다.


. 어플라이언스 전원을 켜고 컨트롤러 LED와 7개 세그먼트 디스플레이를 모니터링합니다.
+
컨트롤러가 성공적으로 부팅되면 7개 세그먼트 디스플레이에 다음이 표시됩니다.

+
** E2800 시리즈 컨트롤러:
+
최종 상태는 입니다 `99`.

** E5500SG 컨트롤러:
+
최종 상태는 입니다 `HA`.



. 어플라이언스 스토리지 노드가 그리드 관리자에 표시되고 경보가 나타나지 않는지 확인합니다.


부품을 교체한 후 키트와 함께 제공된 RMA 지침에 따라 오류가 발생한 부품을 NetApp에 반환합니다. 를 참조하십시오 https://mysupport.netapp.com/site/info/rma["부품 반납 및 교체"^] 페이지를 참조하십시오.

.관련 정보
http://mysupport.netapp.com/info/web/ECMP1658252.html["NetApp E-Series 시스템 문서 사이트"^]
