---
permalink: sg5700/troubleshoot-upgrading-drive-firmware-using-santricity-system-manager.html 
sidebar: sidebar 
keywords: storagegrid, sg5700, troubleshoot, storage node, storage appliance, upgrade, upgrading, firmware, drive, disk, SANtricity System Manager, SANtricity 
summary: SANtricity System Manager를 사용하여 어플라이언스 드라이브의 펌웨어를 업그레이드할 때 발생할 수 있는 오류 해결 
---
= 드라이브 펌웨어의 업그레이드 오류 문제 해결
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SANtricity System Manager를 사용하여 어플라이언스 드라이브의 펌웨어를 업그레이드할 때 발생할 수 있는 오류 해결

* * 할당된 드라이브 실패 *
+
** 이 오류가 발생하는 한 가지 이유는 드라이브에 적절한 서명이 없을 수 있기 때문입니다. 영향을 받는 드라이브가 승인된 드라이브인지 확인합니다. 자세한 내용은 기술 지원 부서에 문의하십시오.
** 드라이브를 교체할 때 교체 드라이브의 용량이 교체 중인 드라이브의 용량보다 크거나 같은지 확인하십시오.
** 스토리지 배열이 I/O를 수신하는 동안 오류가 발생한 드라이브를 교체할 수 있습니다


* * 스토리지 배열 확인 *
+
** 각 컨트롤러에 IP 주소가 할당되었는지 확인합니다.
** 컨트롤러에 연결된 모든 케이블이 손상되지 않았는지 확인합니다.
** 모든 케이블이 단단히 연결되어 있는지 확인합니다.


* * 통합 핫 스페어 드라이브 *
+
펌웨어를 업그레이드하기 전에 이 오류 상태를 수정해야 합니다.

* * 불완전한 볼륨 그룹 *
+
하나 이상의 볼륨 그룹 또는 디스크 풀이 불완전하면 펌웨어를 업그레이드하기 전에 이 오류 조건을 수정해야 합니다.

* * 현재 모든 볼륨 그룹에서 실행 중인 독점 작업(백그라운드 미디어/패리티 검사 제외) *
+
하나 이상의 배타적 작업이 진행 중인 경우 펌웨어를 업그레이드하기 전에 작업을 완료해야 합니다. System Manager를 사용하여 작업 진행률을 모니터링합니다.

* * 볼륨 없음 *
+
펌웨어를 업그레이드하기 전에 누락된 볼륨 상태를 수정해야 합니다.

* * 두 컨트롤러 중 하나가 최적 상태 * 가 아닌 다른 상태입니다
+
스토리지 어레이 컨트롤러 중 하나에 주의가 필요합니다. 펌웨어를 업그레이드하기 전에 이 상태를 수정해야 합니다.

* * 컨트롤러 오브젝트 그래프 * 간에 스토리지 파티션 정보가 일치하지 않습니다
+
컨트롤러의 데이터를 검증하는 동안 오류가 발생했습니다. 이 문제를 해결하려면 기술 지원 부서에 문의하십시오.

* * SPM 데이터베이스 컨트롤러 확인 실패 *
+
컨트롤러에서 스토리지 파티션 매핑 데이터베이스 오류가 발생했습니다. 이 문제를 해결하려면 기술 지원 부서에 문의하십시오.

* * 구성 데이터베이스 검증(스토리지 배열의 컨트롤러 버전에서 지원되는 경우) *
+
컨트롤러에서 구성 데이터베이스 오류가 발생했습니다. 이 문제를 해결하려면 기술 지원 부서에 문의하십시오.

* * MEL 관련 점검 *
+
이 문제를 해결하려면 기술 지원 부서에 문의하십시오.

* * 최근 7일 동안 10개가 넘는 DDE 정보 또는 중요 MEL 이벤트가 보고되었습니다 *
+
이 문제를 해결하려면 기술 지원 부서에 문의하십시오.

* * 지난 7일 동안 2개 이상의 2c 페이지 중요 MEL 이벤트가 보고되었습니다 *
+
이 문제를 해결하려면 기술 지원 부서에 문의하십시오.

* * 최근 7일 동안 성능이 저하된 드라이브 채널 중요 MEL 이벤트가 2개 이상 보고되었습니다 *
+
이 문제를 해결하려면 기술 지원 부서에 문의하십시오.

* * 지난 7일 동안 4개 이상의 중요한 MEL 항목 *
+
이 문제를 해결하려면 기술 지원 부서에 문의하십시오.


