---
permalink: sg5800/replace-controller-5800sg.html 
sidebar: sidebar 
keywords:  
summary:  
---
= StorageGRID SG5800 컨트롤러 교체
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SG5800 컨트롤러가 최적으로 작동하지 않거나 장애가 발생한 경우 교체해야 할 수 있습니다.

.시작하기 전에
* 교체할 컨트롤러와 부품 번호가 동일한 교체 컨트롤러가 있습니다.
* 컨트롤러에 연결된 각 케이블을 식별하는 라벨이 있습니다.


.이 작업에 대해
컨트롤러를 교체하면 어플라이언스 스토리지 노드에 액세스할 수 없습니다.  SG5800 컨트롤러가 충분히 작동하는 경우 이 절차를 시작할 때 제어된 종료를 수행할 수 있습니다.


NOTE: StorageGRID 소프트웨어를 설치하기 전에 컨트롤러를 교체하는 경우 이 절차를 완료한 후 즉시 StorageGRID 어플라이언스 설치 프로그램에 액세스하지 못할 수 있습니다. 어플라이언스와 동일한 서브넷에 있는 다른 호스트에서 StorageGRID 어플라이언스 설치 관리자에 액세스할 수 있지만 다른 서브넷에 있는 호스트에서는 액세스할 수 없습니다. 이 조건은 15분 내에 해결되어야 하며(원래 컨트롤러의 ARP 캐시 항목이 시간 초과될 때), 또는 로컬 라우터 또는 게이트웨이에서 수동으로 이전의 ARP 캐시 항목을 삭제하여 즉시 조건을 지울 수 있습니다.

.단계
. SG5800 컨트롤러를 종료합니다.
+
.. 그리드 노드에 로그인합니다.
+
... 다음 명령을 입력합니다. `ssh admin@grid_node_IP`
... 에 나열된 암호를 입력합니다 `Passwords.txt` 파일.
... 루트로 전환하려면 다음 명령을 입력합니다. `su -`
... 에 나열된 암호를 입력합니다 `Passwords.txt` 파일.
+
루트로 로그인하면 프롬프트가 에서 변경됩니다 `$` 를 선택합니다 `#`.





. SG5800 컨트롤러를 종료합니다.
+
*`shutdown -h now`*

. 컨트롤러에 연결된 StorageGRID 네트워크가 DHCP 서버를 사용하는 경우:
+
.. 교체용 컨트롤러의 포트에 대한 MAC 주소를 확인합니다(컨트롤러의 레이블에 위치).
.. 네트워크 관리자에게 문의하여 교체 컨트롤러의 MAC 주소를 반영하도록 원본 컨트롤러의 IP 주소 설정을 업데이트하십시오.
+

NOTE: 교체용 컨트롤러를 기기에 삽입하기 전에 원래 컨트롤러의 IP 주소가 업데이트되었는지 확인해야 합니다.  그렇지 않으면 컨트롤러가 부팅될 때 새로운 DHCP IP 주소를 얻게 되어 StorageGRID 에 다시 연결하지 못할 수 있습니다.  이 단계는 컨트롤러에 연결된 모든 StorageGRID 네트워크에 적용됩니다.



. 제품에서 컨트롤러를 분리합니다.
+
.. ESD 밴드를 착용하거나 정전기 방지 조치를 취하십시오.
.. 케이블에 레이블을 지정한 다음 케이블 및 SFP를 분리합니다.
+

NOTE: 성능 저하를 방지하려면 케이블을 꼬거나, 접거나, 집거나, 밟지 마십시오.
캠 핸들의 래치를 눌러 제품에서 컨트롤러를 분리한 다음 캠 핸들을 오른쪽으로 엽니다.

.. 양손과 캠 손잡이를 사용하여 제어기를 제품에서 밀어 꺼냅니다.
+

NOTE: 컨트롤러의 무게를 지탱하려면 항상 두 손을 사용하십시오.



. 교체 컨트롤러를 제품에 설치합니다.
+
.. 이동식 덮개가 아래를 향하도록 컨트롤러를 뒤집습니다.
.. 캠 손잡이를 열린 상태에서 컨트롤러를 제품 안으로 끝까지 밀어 넣습니다.
.. 캠 핸들을 왼쪽으로 이동하여 컨트롤러를 제자리에 고정합니다.
.. 케이블을 교체합니다.


. 컨트롤러가 재부팅되고 어플라이언스가 그리드에 다시 연결되면 어플라이언스 스토리지 노드가 그리드 관리자에 나타나고 알람이 나타나지 않는지 확인합니다.


부품을 교체한 후 키트와 함께 제공된 RMA 지침에 따라 오류가 발생한 부품을 NetApp에 반환합니다. 를 참조하십시오 https://mysupport.netapp.com/site/info/rma["부품 반납 및 교체"] 페이지를 참조하십시오.
