---
permalink: sg5800/replace-drives-12-24.html 
sidebar: sidebar 
keywords: E4000 replace drive, replacing E4000 drive, E4000 replace drive, replacing E4000 drive, E4000, E-Series, eseries. sg5812 
summary: SG5812에서 드라이브를 교체할 수 있습니다. 
---
= SG5812의 드라이브를 교체합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SG5812에서 드라이브를 교체할 수 있습니다.

.이 작업에 대해
StorageGRID 그리드 관리자는 어플라이언스 상태를 모니터링하고 드라이브 장애가 발생하면 경고를 발생시킵니다.  그리드 관리자가 경고를 발생시키거나 언제든지 SANtricity 시스템 관리자의 Recovery Guru를 사용하여 장애가 발생한 특정 드라이브에 대한 자세한 정보를 얻을 수 있습니다.  드라이브에 오류가 발생하면 황색 주의 LED가 켜집니다. 스토리지 배열이 I/O를 수신하는 동안 오류가 발생한 드라이브를 핫 스왑할 수 있습니다

.시작하기 전에
* 드라이브 취급 요구 사항을 검토합니다
* 다음 사항을 확인하십시오.
+
** NetApp에서 지원하는 컨트롤러 쉘프 또는 드라이브 쉘프 대체 드라이브
** ESD 밴드이거나 다른 정전기 방지 예방 조치를 취했습니다.
** 컨트롤러의 SANtricity 시스템 관리자에 액세스할 수 있는 브라우저가 있는 관리 스테이션. System Manager 인터페이스를 열려면 브라우저에서 컨트롤러의 도메인 이름 또는 IP 주소를 가리킵니다.






== 1단계: 드라이브 교체 준비

SANtricity 시스템 관리자의 Recovery Guru를 확인하고 필수 단계를 완료하여 드라이브를 교체할 준비를 합니다. 그런 다음 장애가 발생한 구성 요소를 찾을 수 있습니다.

.단계
. SANtricity System Manager의 Recovery Guru에서 드라이브 오류가 발생했다는 메시지가 표시되지만 아직 드라이브에 오류가 발생하지 않은 경우 Recovery Guru의 지침에 따라 드라이브에 장애가 발생한 것입니다.
. 필요한 경우 SANtricity 시스템 관리자를 사용하여 적합한 교체 드라이브가 있는지 확인하십시오.
+
.. 하드웨어 * 를 선택합니다.
.. 쉘프 그래픽에서 장애가 발생한 드라이브를 선택합니다.
.. 드라이브를 클릭하여 상황에 맞는 메뉴를 표시한 다음 * 설정 보기 * 를 선택합니다.
.. 교체 드라이브의 용량이 교체 중인 드라이브와 같거나 큰지, 예상 기능이 있는지 확인합니다.
+
예를 들어, 하드 디스크 드라이브(HDD)를 SSD(Solid State Disk)로 교체하려고 시도하지 마십시오. 마찬가지로, 보안 가능 드라이브를 교체하는 경우 교체 드라이브도 안전하게 사용할 수 있는지 확인하십시오.



. 필요한 경우 SANtricity 시스템 관리자를 사용하여 스토리지 배열 내의 드라이브를 찾습니다. 하드웨어 페이지의 드라이브 컨텍스트 메뉴에서 * 로케이터 표시등 켜기 * 를 선택합니다.
+
드라이브 주의 LED(주황색)가 깜박여 교체할 드라이브를 확인할 수 있습니다.

+

NOTE: 베젤이 있는 쉘프에 드라이브를 장착하는 경우 드라이브 LED를 보려면 베젤을 분리해야 합니다.





== 2단계: 장애가 발생한 드라이브를 제거합니다

장애가 발생한 드라이브를 제거하여 새 드라이브로 교체합니다.

.단계
. 교체용 드라이브의 포장을 풀고 선반 근처의 평평한 정전기 방지 표면에 놓습니다.
+
포장재를 모두 보관하십시오.

. 오류가 발생한 드라이브의 분리 단추를 누릅니다.
. 캠 핸들을 열고 드라이브를 살짝 밀어 꺼냅니다.
. 30초 동안 기다립니다.
. 양손을 사용하여 선반에서 드라이브를 분리합니다.
. 드라이브를 자기 들판 반대쪽으로 정전기 방지 쿠션 처리된 표면에 놓습니다.
. 소프트웨어가 드라이브가 제거되었음을 인식할 때까지 30초 동안 기다립니다.
+

NOTE: 활성 드라이브를 실수로 분리한 경우 30초 이상 기다린 다음 다시 설치합니다. 복구 절차는 스토리지 관리 소프트웨어를 참조하십시오.





== 3단계: 새 드라이브를 설치합니다

새 드라이브를 설치하여 장애가 발생한 드라이브를 교체합니다.


CAUTION: 장애가 발생한 드라이브를 제거한 후 가능한 한 빨리 교체용 드라이브를 설치합니다. 그렇지 않으면 장비가 과열될 위험이 있습니다.

.단계
. 캠 핸들을 엽니다.
. 두 손으로 교체용 드라이브를 열린 베이에 삽입하고 드라이브가 멈출 때까지 힘껏 밉니다.
. 드라이브가 미드플레인에 완전히 장착되고 손잡이가 딸깍 소리를 내며 제자리에 고정될 때까지 캠 핸들을 천천히 닫습니다.
+
드라이브가 올바르게 삽입되면 드라이브의 녹색 LED가 켜집니다.

+

NOTE: 구성에 따라 컨트롤러가 자동으로 새 드라이브에 데이터를 재구성합니다. 쉘프에서 핫 스페어 드라이브를 사용하는 경우, 컨트롤러는 핫 스페어에서 전체 재구성을 수행해야 데이터를 교체한 드라이브에 복사할 수 있습니다. 이 재구성 프로세스는 이 절차를 완료하는 데 필요한 시간을 증가시킵니다.





== 4단계: 드라이브 교체 완료

드라이브 교체를 완료하여 새 드라이브가 올바르게 작동하는지 확인합니다.

.단계
. 교체한 드라이브의 전원 LED 및 주의 LED를 확인합니다. (드라이브를 처음 삽입할 때 주의 LED가 켜져 있을 수 있습니다. 하지만 1분 이내에 LED가 꺼집니다.)
+
** 전원 LED가 켜져 있거나 깜박이고 주의 LED가 꺼져 있습니다. 새 드라이브가 올바르게 작동하고 있음을 나타냅니다.
** 전원 LED가 꺼져 있음: 드라이브가 올바르게 설치되지 않았을 수 있음을 나타냅니다. 드라이브를 분리하고 30초 정도 기다린 다음 다시 설치합니다.
** 주의 LED가 켜짐: 새 드라이브에 결함이 있을 수 있음을 나타냅니다. 다른 새 드라이브로 교체합니다.


. SANtricity 시스템 관리자의 Recovery Guru에서 여전히 문제가 나타나면 * Recheck * 를 선택하여 문제가 해결되었는지 확인합니다.
. Recovery Guru에서 드라이브 재구성이 자동으로 시작되지 않았다고 표시되면 다음과 같이 수동으로 재구성을 시작합니다.
+

NOTE: 기술 지원 부서 또는 Recovery Guru에서 지시한 경우에만 이 작업을 수행하십시오.

+
.. 하드웨어 * 를 선택합니다.
.. 교체한 드라이브를 클릭합니다.
.. 드라이브의 컨텍스트 메뉴에서 * reconstruct * 를 선택합니다.
.. 이 작업을 수행할지 확인합니다.
+
드라이브 재구성이 완료되면 볼륨 그룹이 Optimal(최적) 상태에 있습니다.



. 필요한 경우 베젤을 다시 설치합니다.
. 키트와 함께 제공된 RMA 지침에 설명된 대로 오류가 발생한 부품을 NetApp에 반환합니다.


.다음 단계
드라이브 교체가 완료되었습니다. 일반 작업을 다시 시작할 수 있습니다.
