---
permalink: commonhardware/considerations-and-requirements-for-appliance-node-cloning.html 
sidebar: sidebar 
keywords: storagegrid, clone appliance node, cloning appliance node 
summary: 어플라이언스 노드를 클론 복제하기 전에 고려 사항 및 요구 사항을 이해해야 합니다. 
---
= 어플라이언스 노드 클론 생성을 위한 고려 사항 및 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
어플라이언스 노드를 클론 복제하기 전에 고려 사항 및 요구 사항을 이해해야 합니다.



== 교체 어플라이언스에 대한 하드웨어 요구 사항

교체 제품이 다음 기준을 충족하는지 확인하십시오.

* 소스 노드(어플라이언스 교체)와 타겟(새) 어플라이언스는 어플라이언스의 유형이 동일해야 합니다.
+
** 관리 노드 어플라이언스 또는 게이트웨이 노드 어플라이언스를 새 서비스 어플라이언스에만 복제할 수 있습니다.
** 스토리지 노드 어플라이언스는 새 스토리지 어플라이언스에만 복제할 수 있습니다.


* 관리 노드 또는 게이트웨이 노드 어플라이언스의 경우 소스 노드 어플라이언스 및 타겟 어플라이언스가 동일한 유형의 어플라이언스일 필요는 없지만 어플라이언스 유형을 변경하려면 케이블이나 SFP 모듈을 교체해야 할 수 있습니다.
+
예를 들어 SG1000 노드 어플라이언스를 SG100으로 교체하거나 SG100 어플라이언스를 SG1000 어플라이언스로 교체할 수 있습니다.

* 스토리지 노드 어플라이언스의 경우 소스 노드 어플라이언스와 타겟 어플라이언스는 어플라이언스 유형이 같을 필요는 없지만 타겟 어플라이언스의 스토리지 용량은 소스 어플라이언스보다 커야 합니다.
+
예를 들어 SG6000 어플라이언스로 SG6000 노드 어플라이언스를 교체할 수 있습니다.



StorageGRID 설치 시 특정 어플라이언스 노드를 클론 복제하기 위해 호환되는 교체 어플라이언스를 선택하는 데 도움이 필요하면 StorageGRID 영업 담당자에게 문의하십시오.



== 어플라이언스 노드의 클론을 생성할 준비를 합니다

어플라이언스 노드를 클론 복제하기 전에 다음 정보가 있어야 합니다.

* 초기 설치 중에 대상 어플라이언스와 함께 사용할 수 있도록 네트워크 관리자로부터 Grid Network에 대한 임시 IP 주소를 얻습니다. 소스 노드가 관리 네트워크 또는 클라이언트 네트워크에 속한 경우 이러한 네트워크에 대한 임시 IP 주소를 가져옵니다.
+
임시 IP 주소는 일반적으로 클론 생성 중인 소스 노드 어플라이언스와 동일한 서브넷에 있으며 클론 생성이 완료된 후에는 필요하지 않습니다. 클론 생성 연결을 설정하려면 소스 및 타겟 어플라이언스가 모두 StorageGRID의 기본 관리 노드에 연결되어야 합니다.

* StorageGRID 네트워크 성능 또는 데이터 가용성을 저하시키지 않으면서 최상의 데이터 전송 성능을 제공하는 데이터 전송 트래픽 복제에 사용할 네트워크를 결정합니다.
+

NOTE: 클론 데이터 전송에 1GbE 관리자 네트워크를 사용하면 클론 생성 속도가 느려집니다.

* 타겟 어플라이언스에서 KMS(키 관리 서버)를 사용하여 노드 암호화를 사용할 것인지 확인하여 클론 생성 전에 초기 타겟 어플라이언스 설치 중에 노드 암호화를 활성화할 수 있도록 합니다. 에 설명된 대로 소스 어플라이언스 노드에서 노드 암호화가 활성화되어 있는지 확인할 수 있습니다 link:../installconfig/optional-enabling-node-encryption.html["노드 암호화 활성화 중"].
+
소스 노드와 타겟 어플라이언스의 노드 암호화 설정이 다를 수 있습니다. 데이터 해독 및 암호화는 데이터 전송 중에 그리고 타겟 노드가 다시 시작되고 그리드에 조인될 때 자동으로 수행됩니다.

* 타겟 어플라이언스의 RAID 모드를 기본 설정에서 변경해야 하는지 확인하여 클론 생성 전에 초기 타겟 어플라이언스 설치 중에 이 정보를 지정할 수 있습니다. Grid Manager의 * nodes * 페이지에서 소스 어플라이언스 노드의 현재 RAID 모드에 대한 정보를 볼 수 있습니다. 어플라이언스에 대한 * Storage * 탭을 선택합니다.
+
소스 노드와 타겟 어플라이언스의 RAID 설정은 다를 수 있습니다.

* 노드 클론 생성 프로세스를 완료하는 데 충분한 시간을 확보하십시오. 운영 스토리지 노드에서 타겟 어플라이언스로 데이터를 전송하려면 며칠이 걸릴 수 있습니다. 비즈니스에 미치는 영향을 최소화할 수 있도록 한 번에 클론 복제 일정을 수립합니다.
* 한 번에 하나의 어플라이언스 노드만 복제해야 합니다. 클론 생성 시 다른 StorageGRID 유지 보수 기능을 동시에 수행할 수 없습니다.
* 어플라이언스 노드를 복제한 후에는 설치 전 상태로 반환된 소스 어플라이언스를 대상으로 사용하여 다른 호환 노드 어플라이언스를 복제할 수 있습니다.

