---
permalink: commonhardware/how-appliance-node-cloning-works.html 
sidebar: sidebar 
keywords: storagegrid, appliance node cloning, appliance node clone 
summary: StorageGRID에서 어플라이언스 노드를 클론 복제하여 새로운 설계 또는 향상된 기능의 어플라이언스를 사용할 수 있습니다. 클론 복제는 기존 노드에 대한 모든 정보를 새 어플라이언스로 전송하고, 수행하기 쉬운 하드웨어 업그레이드 프로세스를 제공하며, 어플라이언스 교체를 위한 서비스 해제 및 확장 대안을 제공합니다. 
---
= 어플라이언스 노드 클론 생성: 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID에서 어플라이언스 노드를 클론 복제하여 새로운 설계 또는 향상된 기능의 어플라이언스를 사용할 수 있습니다. 클론 복제는 기존 노드에 대한 모든 정보를 새 어플라이언스로 전송하고, 수행하기 쉬운 하드웨어 업그레이드 프로세스를 제공하며, 어플라이언스 교체를 위한 서비스 해제 및 확장 대안을 제공합니다.

어플라이언스 노드 클론 복제를 사용하면 그리드에서 기존 어플라이언스 노드(소스)를 동일한 논리적 StorageGRID 사이트의 일부인 호환 어플라이언스(타겟)로 쉽게 교체할 수 있습니다. 이 프로세스는 모든 데이터를 새 어플라이언스에 전송하여 이전 어플라이언스 노드를 교체하고 이전 어플라이언스를 설치 전 상태로 둡니다.



== 어플라이언스 노드를 클론 복제해야 하는 이유

다음과 같은 경우에 어플라이언스 노드를 클론 복제할 수 있습니다.

* 수명이 다 된 제품은 교체하십시오.
* 기존 노드를 업그레이드하여 개선된 어플라이언스 기술을 활용하십시오.
* StorageGRID 시스템에서 스토리지 노드 수를 변경하지 않고 그리드 스토리지 용량을 늘립니다.
* RAID 모드를 DDP-8에서 DDP-16 또는 RAID-6으로 변경하는 것과 같은 스토리지 효율성을 향상시킵니다.
* 외부 키 관리 서버(KMS)를 사용할 수 있도록 노드 암호화를 효율적으로 구현합니다.




== 어떤 StorageGRID 네트워크가 사용됩니까?

클론 복제는 세 StorageGRID 네트워크 중 하나를 통해 소스 노드에서 타겟 어플라이언스로 직접 데이터를 전송합니다. 그리드 네트워크는 일반적으로 사용되지만 소스 어플라이언스가 이러한 네트워크에 연결되어 있는 경우 관리 네트워크 또는 클라이언트 네트워크를 사용할 수도 있습니다. StorageGRID 네트워크 성능 또는 데이터 가용성을 저하시키지 않으면서 최상의 데이터 전송 성능을 제공하는 트래픽 클론 생성에 사용할 네트워크를 선택하십시오.

교체 어플라이언스를 설치할 때 StorageGRID 연결 및 데이터 전송을 위한 임시 IP 주소를 지정해야 합니다. 교체 어플라이언스는 대체 어플라이언스와 동일한 네트워크에 속하므로 교체 어플라이언스에서 이러한 각 네트워크에 대한 임시 IP 주소를 지정해야 합니다.



== 대상 어플라이언스 호환성

교체 어플라이언스는 교체 중인 소스 노드와 유형이 같아야 하며 두 어플라이언스 모두 동일한 논리 StorageGRID 사이트의 일부여야 합니다.

* 교체 서비스 어플라이언스는 교체되는 관리 노드 또는 게이트웨이 노드와 다를 수 있습니다.
+
** SG100 소스 노드 어플라이언스를 SG1000 서비스 대상 어플라이언스에 복제하여 관리자 노드 또는 게이트웨이 노드에 더 큰 기능을 제공할 수 있습니다.
** SG1000 소스 노드 어플라이언스를 SG100 서비스 대상 어플라이언스에 복제하여 SG1000을 보다 까다로운 응용 프로그램에 재배포할 수 있습니다.
+
예를 들어 SG1000 소스 노드 어플라이언스를 관리 노드로 사용하고 있고 이를 전용 로드 밸런싱 노드로 사용하려는 경우

** SG1000 소스 노드 어플라이언스를 SG100 서비스 대상 어플라이언스로 교체하면 네트워크 포트의 최대 속도가 100GbE에서 25GbE로 줄어듭니다.
** 서비스 어플라이언스에는 서로 다른 네트워크 커넥터가 있습니다. 어플라이언스 유형을 변경하려면 케이블이나 SFP 모듈을 교체해야 할 수 있습니다.


* 교체 스토리지 어플라이언스의 용량은 교체할 스토리지 노드보다 커야 합니다.
+
** 타겟 스토리지 어플라이언스의 드라이브 수가 소스 노드와 동일한 경우 타겟 어플라이언스의 드라이브 용량이 TB여야 합니다.
** 소스 노드에서 사용된 것과 동일한 RAID 모드를 타겟 노드에서 사용하려는 경우 또는 스토리지 효율성이 떨어지는 RAID 모드(예: RAID 6에서 DDP로 전환)에서는 타겟 어플라이언스의 드라이브가 소스 어플라이언스의 드라이브보다 크거나(TB 단위) 않아야 합니다.
** SSD(Solid State Drive) 설치로 인해 타겟 스토리지 어플라이언스에 설치된 표준 드라이브 수가 소스 노드의 드라이브 수보다 적은 경우(TB) 타겟 어플라이언스에 있는 표준 드라이브의 전체 스토리지 용량 소스 스토리지 노드에 있는 모든 드라이브의 총 기능 드라이브 용량을 초과해야 합니다.
+
예를 들어, 60개의 드라이브를 사용하여 SG5760 소스 스토리지 노드 어플라이언스를 58개의 표준 드라이브를 사용하는 SG6060 타겟 어플라이언스에 클론 생성할 경우, 스토리지 용량을 유지하기 위해 클론 생성 전에 더 큰 드라이브를 SG6060 타겟 어플라이언스에 설치해야 합니다. (타겟 어플라이언스에 SSD가 포함된 드라이브 슬롯 2개는 총 어플라이언스 스토리지 용량에 포함되지 않습니다.)

+
하지만 60 드라이브 SG5760 소스 노드 어플라이언스가 SANtricity Dynamic Disk Pools DDP-8로 구성된 경우, DDP-16을 사용하여 58 드라이브 동일 크기 드라이브 SG6060 타겟 어플라이언스를 구성하면 스토리지 효율성이 향상되기 때문에 SG6060 어플라이언스가 유효한 클론 타겟이 될 수 있습니다.

+
Grid Manager의 * nodes * 페이지에서 소스 어플라이언스 노드의 현재 RAID 모드에 대한 정보를 볼 수 있습니다. 어플라이언스에 대한 * Storage * 탭을 선택합니다.



* 타겟 스토리지 어플라이언스의 볼륨 수는 소스 노드의 볼륨 수보다 크거나 같아야 합니다. 오브젝트 저장소 볼륨(rangedb)이 16개인 소스 노드를 12개의 오브젝트 저장소 볼륨이 있는 타겟 스토리지 어플라이언스에 클론 복제할 수 없습니다. 타겟 어플라이언스에 소스 노드보다 용량이 더 큰 경우에도 마찬가지입니다. 오브젝트 저장소 볼륨이 12개뿐인 SGF6112 스토리지 어플라이언스를 제외하고 대부분의 스토리지 어플라이언스에는 16개의 오브젝트 저장소 볼륨이 있습니다.




== 클론이 생성되지 않는 정보는 무엇입니까?

클론 생성 중에는 다음 어플라이언스 구성이 교체 어플라이언스로 전송되지 않습니다. 교체 어플라이언스의 초기 설정 중에 구성해야 합니다.

* BMC 인터페이스
* 네트워크 링크
* 노드 암호화 상태입니다
* SANtricity 시스템 관리자(스토리지 노드의 경우)
* RAID 모드(스토리지 노드의 경우)




== 클론 생성을 방해하는 문제는 무엇입니까?

클론 복제 중에 다음 문제가 발생하면 복제 프로세스가 중지되고 오류 메시지가 생성됩니다.

* 네트워크 구성이 잘못되었습니다
* 소스와 타겟 어플라이언스 간의 연결 부족
* 소스 및 타겟 어플라이언스가 호환되지 않습니다
* 스토리지 노드의 경우 용량이 부족한 대체 어플라이언스입니다


복제를 계속하려면 각 문제를 해결해야 합니다.
