---
permalink: commonhardware/index.html 
sidebar: sidebar 
keywords: maintain overview, maintenance overview, about maintain, about maintenance 
summary: 이 지침에 따라 StorageGRID 시스템을 유지보수하십시오. 
---
= 노드 유지 보수를 위한 일반 절차: 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 지침에 따라 StorageGRID 시스템을 유지보수하십시오.



== 참조하십시오

이 지침에서는 소프트웨어 핫픽스 적용, 그리드 노드 복구, 장애가 발생한 사이트 복구, 그리드 노드 또는 전체 사이트 파기, 네트워크 유지보수 수행, 호스트 레벨 및 미들웨어 유지보수 절차 수행, 그리드 노드 절차 수행 방법 등 모든 노드에 공통된 절차를 설명합니다.


NOTE: 이 지침에서 ""Linux"는 Red Hat ® Enterprise Linux ®, Ubuntu ® 또는 Debian ® 배포를 나타냅니다. 를 사용합니다 https://imt.netapp.com/matrix/#welcome["NetApp 상호 운용성 매트릭스 툴(IMT)"^] 를 클릭하여 지원되는 버전 목록을 가져옵니다.



== 시작하기 전에

* StorageGRID 시스템에 대한 폭넓은 지식을 갖추고 있습니다.
* StorageGRID 시스템의 토폴로지를 검토했으며 그리드 구성을 이해했습니다.
* 당신은 모든 지침을 정확하게 따르고 모든 경고에 주의를 기울여야 한다는 것을 이해합니다.
* 설명되지 않은 유지보수 절차는 지원되지 않거나 서비스 계약이 필요하다는 것을 알고 있습니다.




== 어플라이언스에 대한 유지보수 절차

각 StorageGRID 어플라이언스 유형에 대한 구체적인 유지보수 절차는 어플라이언스 유지보수 섹션에 나와 있습니다.

* link:../sg6100/index.html["SG6100 어플라이언스를 유지보수 합니다"]
* link:../sg6000/index.html["SG6000 어플라이언스를 유지보수하십시오"]
* link:../sg5800/index.html["SG5800 어플라이언스를 유지 관리합니다"]
* link:../sg5700/index.html["SG5700 어플라이언스 유지"]
* link:../sg110-1100/index.html["SG110 및 SG1100 어플라이언스를 유지 관리합니다"]
* link:../sg100-1000/index.html["SG100 및 SG1000 어플라이언스는 유지해야 합니다"]

