---
permalink: commonhardware/locate-mac-address.html 
sidebar: sidebar 
keywords: storagegrid, mac, mac address 
summary: 어플라이언스 교체 후 MAC 주소 참조를 업데이트해야 하는 경우도 있습니다. 
---
= MAC 주소 참조를 업데이트합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
어플라이언스 교체 후 MAC 주소 참조를 업데이트해야 하는 경우도 있습니다.

.이 작업에 대해
교체 중인 어플라이언스의 네트워크 인터페이스가 DHCP용으로 구성된 경우 교체 어플라이언스의 MAC 주소를 참조하도록 DHCP 서버의 영구 DHCP 임대 할당을 업데이트해야 할 수 있습니다. 업데이트는 교체 어플라이언스에 예상 IP 주소가 할당되도록 합니다.

.단계
. 제품 앞면에 있는 레이블을 찾습니다. 레이블에는 어플라이언스의 BMC 관리 포트에 대한 MAC 주소가 나열됩니다.
. 관리 네트워크 포트의 MAC 주소를 확인하려면 레이블의 16진수에 * 2 * 를 추가해야 합니다.
+
예를 들어 레이블의 MAC 주소가 * 09 * 로 끝나는 경우 관리 포트의 MAC 주소는 * 0B * 로 끝납니다. 레이블의 MAC 주소가 * (_y_) FF * 로 끝나는 경우 관리 포트의 MAC 주소는 * (_y_+1) 01 * 로 끝납니다.

+
Windows에서 계산기를 열고, Programmer 모드로 설정하고, Hex를 선택하고, MAC 주소를 입력한 다음, * + 2 = * 를 입력하여 이 계산을 쉽게 수행할 수 있습니다.

. 제거한 어플라이언스의 DNS/네트워크 및 IP 주소를 대체 어플라이언스의 MAC 주소와 연관시킬 것을 네트워크 관리자에게 요청하십시오.
+

CAUTION: 교체 어플라이언스에 전원을 공급하려면 먼저 원래 어플라이언스의 모든 IP 주소가 업데이트되었는지 확인해야 합니다. 그렇지 않으면 장치가 부팅될 때 새 DHCP IP 주소를 받게 되며 StorageGRID에 다시 연결할 수 없게 됩니다. 이 단계는 어플라이언스에 연결된 모든 StorageGRID 네트워크에 적용됩니다.

+

NOTE: 원래 어플라이언스가 고정 IP 주소를 사용하는 경우 새 어플라이언스는 제거된 어플라이언스의 IP 주소를 자동으로 채택합니다.


